# Generated by Django 3.2.2 on 2021-05-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210518_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='ListingComments', to='auctions.Commentary'),
        ),
    ]
