# Generated by Django 3.2.2 on 2021-05-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='NoReasonToUseThisRN', to='auctions.Listing'),
        ),
    ]
