# Generated by Django 3.2.2 on 2021-05-21 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_user_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='listing',
            name='usersWatchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='UserWatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
