# Generated by Django 3.2.2 on 2021-05-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210520_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='usersWatchlist',
        ),
        migrations.AddField(
            model_name='user',
            name='userWatchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='UserWatchlist', to='auctions.Listing'),
        ),
    ]
