# Generated by Django 3.2.2 on 2021-05-23 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_rename_number_bid_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bidSoFar',
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ListingHigherBid', to='auctions.listing'),
        ),
    ]
