# Generated by Django 3.2.2 on 2021-05-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210523_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ManyToManyField(null=True, related_name='ListingHigherBid', to='auctions.Listing'),
        ),
    ]
